# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='apiapp.Exam'),
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set([('order', 'exam')]),
        ),
        migrations.AlterUniqueTogether(
            name='step',
            unique_together=set([('order', 'problem')]),
        ),
    ]
