# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0002_auto_20160115_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='step',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='apiapp.Problem'),
        ),
    ]
