# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-08 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0003_auto_20160118_2318'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['display_text']},
        ),
        migrations.AlterModelOptions(
            name='step',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='problem',
            name='display_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
