# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0004_auto_20160308_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ip', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=256)),
                ('int1', models.BigIntegerField()),
                ('int2', models.BigIntegerField()),
                ('string1', models.CharField(blank=True, max_length=256)),
                ('string2', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['order']},
        ),
    ]
