# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiapp', '0005_auto_20160416_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='int1',
            field=models.BigIntegerField(blank=True, default=-1),
        ),
        migrations.AlterField(
            model_name='event',
            name='int2',
            field=models.BigIntegerField(blank=True, default=-1),
        ),
    ]
